### ISSUE TITLE
CSS 매번 찾기 귀찮은 것들 정리

### ISSUE THREAD

**Issue by zeroFruit** [Nexters/flass#83]
### div 버튼안에 텍스트 수평, 수직으로 가운데로 정렬하기
```react
<div className="btn">
  버튼
</div>
```
```css
.btn {
  display: flex;
  justify-contents: center;
  align-items: center;
}
```
